SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 100 AND 105;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (151 , 152, 153, 154 , 155);
SELECT * FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE 'p%';
SELECT * FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE '%a';
SELECT * FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE '%a%';
SELECT * FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE '__e%';
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL ;
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL ;
INSERT INTO EMPLOYEES(employee_id, first_name, last_name, email,hire_date, job_id, salary, manager_id)
VALUES(300, 'Ahmed', 'Ali', 'AALI',SYSDATE, 'IT_PROG', 5000, NULL);
SELECT * FROM EMPLOYEES WHERE JOB_ID='AD_VP'OR JOB_ID='IT_PROG'; 
SELECT * FROM EMPLOYEES ORDER BY last_name asc;
SELECT * FROM EMPLOYEES ORDER BY hire_date desc;
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID ASC,SALARY DESC ;
SELECT LOWER(last_name)FROM EMPLOYEES;
SELECT UPPER(first_name)FROM EMPLOYEES;
SELECT INITCAP(first_name),INITCAP(last_name)FROM employees;
SELECT * FROM employees WHERE LOWER(last_name) = 'smith';






